version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "Project2_rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  buyer-service:
    build: ./BuyerService
    ports:
      - "8002:8002"
    volumes:
      - ./BuyerService:/app
      - ./BuyerService/data:/app/data  # Make sure your db file is here for persistence
  merchant-service:
    build: ./MerchantService
    ports:
      - "8001:8001"
    volumes:
      - ./MerchantService:/app
      - ./MerchantService/data:/app/data  # Make sure your db file is here for persistence

  inventory-service:
    build: ./InventoryService
    ports:
      - "8003:8003"
    volumes:
      - ./InventoryService:/app
      - ./InventoryService/data:/app/data 
  payment-service:
    build: ./PaymentService
    volumes:
      - ./PaymentService:/app
      - ./PaymentService/data:/app/data
volumes:
  buyer-service-data:
  inventory-service-data:
