version: "3.8"

services:
  buyer-service:
    build: ./BuyerService
    ports:
      - "8002:8002"
    volumes:
      - ./BuyerService:/app
      - ./BuyerService/data:/app/data  # Make sure your db file is here for persistence

volumes:
  buyer-service-data: