version: "3.8"

services:
  buyer_service:
    build: ./BuyerService
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data  # Make sure your db file is here for persistence

volumes:
  buyer-db: