version: '3.8'
services:
  orderservice:
    build:
      context: ./OrderService
    container_name: orderservice
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - orderservice_db

  # Other services such as BuyerService, MerchantService, InventoryService, and EmailService

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  orderservice_db:
    image: postgres:latest
    container_name: orderservice_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - orderservice_db_data:/var/lib/postgresql/data

volumes:
  orderservice_db_data:
