version: "3.8"

services:
  buyer-service:
    build: ./BuyerService
    ports:
      - "8002:8002"
    volumes:
      - ./BuyerService:/app
      - ./BuyerService/data:/app/data  # Make sure your db file is here for persistence

  inventory-service:
    build: ./InventoryService
    ports:
      - "8003:8003"
    volumes:
      - ./InventoryService:/app
      - ./InventoryService/data:/app/data 

volumes:
  buyer-service-data:
  inventory-service-data:
