version: "3.8"

services:
  buyer-service:
    build: ./BuyerService
    ports:
      - "8002:8002"
    volumes:
      - ./BuyerService:/app
      - ./BuyerService/data:/app/data  # Make sure your db file is here for persistence
  merchant-service:
    build: ./MerchantService
    ports:
      - "8001:8001"
    volumes:
      - ./MerchantService:/app
      - ./MerchantService/data:/app/data  # Make sure your db file is here for persistence

  inventory-service:
    build: ./InventoryService
    ports:
      - "8003:8003"
    volumes:
      - ./InventoryService:/app
      - ./InventoryService/data:/app/data 
  
  email-service:
    build: ./EmailService
    ports:
      - "8004:8004"

volumes:
  buyer-service-data:
  inventory-service-data:
